export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const USER_NO_AUTHENTICATION = 'USER_NO_AUTHENTICATION';

export const FETCH_AUDIO_RECORDINGS = 'FETCH_AUDIO_RECORDINGS';